modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="alloyspawn"
version="1.0.0"
displayName="AlloySpawn"
displayURL="https://ghluka.github.io/alloyspawn"
logoFile="logo.png"
credits="created using MCreator"
authors="ghluka, MCreator"
description="All items and mobs featured in this mod are works of parody and satire intended as commentary on consumer culture and product safety concerns. They are not meant to be interpreted as factual claims about any real-world brands, companies, or persons. The effects depicted in the mod are purely fictional and for entertainment purposes only; they do not allege that any similar effects would occur in the real world. Any similarities to real-world brands or individuals are used for satirical purposes and are not meant to cause harm, defame, or mislead users."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.alloyspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration